name: TestEnv1
values:
  - key: BaseUrl
    value: ''
  - key: accessToken
    value: ''
  - key: product_id
    value: ''
  - key: searched_product_id
    value: ''
  - key: cart_id
    value: ''
  - key: saved_image_blob
    value: ''
  - key: image_size
    value: ''
  - key: image_color
    value: ''
